#version: '3.8'

services:
  # Servicio 1: Aplicación Django
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app  # "Espejo": Lo que edites en tu PC se ve en el contenedor al instante
    ports:
      - "8000:8000" # Accederás vía localhost:8000
    depends_on:
      - db
    environment:
      - DB_NAME=finance_db
      - DB_USER=finance_user
      - DB_PASSWORD=finance_pass
      - DB_HOST=db
      - EMAIL_HOST=imap.gmail.com
      - EMAIL_PORT=993
      - EMAIL_USER=geotiglab@gmail.com
      - EMAIL_PASS=ztkufjotmxkuhaof
  # Servicio 2: Aplicación Frontend con Vite
  frontend:
    image: node:20-slim
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules 
    ports:
      - "5173:5173"
    # Comando para desarrollo: instala dependencias y levanta el servidor
    command: sh -c "npm install && npm run dev -- --host"

  # Servicio 2: Base de datos PostgreSQL
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persistencia de datos
    environment:
      - POSTGRES_DB=finance_db
      - POSTGRES_USER=finance_user
      - POSTGRES_PASSWORD=finance_pass

volumes:
  postgres_data: